# Generated by Django 5.2.3 on 2025-06-14 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VesselParticulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=255, unique=True, verbose_name='Vessel Name')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Capacity')),
                ('number_of_decks', models.IntegerField(blank=True, null=True, verbose_name='Number of Decks')),
                ('general_notes', models.TextField(blank=True, null=True, verbose_name='General Notes')),
                ('additional_hazards', models.TextField(blank=True, null=True, verbose_name='Additional Hazards')),
                ('deck_layout_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Deck Layout Link')),
                ('risk_assessment_document_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Risk Assessment Document Link')),
            ],
            options={
                'verbose_name': 'Vessel Detail',
                'verbose_name_plural': 'Vessel Details',
                'ordering': ['vessel_name'],
            },
        ),
        migrations.CreateModel(
            name='VesselComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=255, verbose_name='Comment Title')),
                ('comment_details', models.TextField(verbose_name='Comment Details')),
                ('date_of_comment', models.DateTimeField(verbose_name='Date of Comment')),
                ('comment_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment By')),
                ('related_vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='core_app.vesselparticulars', verbose_name='Related Vessel')),
            ],
            options={
                'verbose_name': 'Vessel Comment',
                'verbose_name_plural': 'Vessel Comments',
                'ordering': ['-date_of_comment'],
            },
        ),
        migrations.CreateModel(
            name='VesselDeckHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_number', models.CharField(max_length=50, verbose_name='Deck Number')),
                ('average_deck_height_m', models.FloatField(blank=True, null=True, verbose_name='Average Deck Height (m)')),
                ('deck_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Deck Type')),
                ('notes', models.TextField(blank=True, null=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_heights', to='core_app.vesselparticulars', verbose_name='Vessel')),
            ],
            options={
                'verbose_name': 'Vessel Deck Height',
                'verbose_name_plural': 'Vessel Deck Heights',
                'ordering': ['vessel', 'deck_number'],
                'unique_together': {('vessel', 'deck_number')},
            },
        ),
    ]
