# Generated by Django 5.2.3 on 2025-06-14 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VesselParticulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=255, unique=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('number_of_decks', models.IntegerField(blank=True, null=True)),
                ('general_notes', models.TextField(blank=True, null=True)),
                ('additional_hazards', models.TextField(blank=True, null=True)),
                ('deck_layout_link', models.URLField(blank=True, max_length=500, null=True)),
                ('risk_assessment_document_link', models.URLField(blank=True, max_length=500, null=True)),
                ('vessel_info_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VesselComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=255)),
                ('comment_details', models.TextField()),
                ('date_of_comment', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_by', models.CharField(blank=True, max_length=100, null=True)),
                ('related_vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.vesselparticulars')),
            ],
            options={
                'ordering': ['-date_of_comment'],
            },
        ),
        migrations.CreateModel(
            name='VesselDeckHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_id', models.IntegerField(blank=True, null=True)),
                ('deck_name', models.CharField(blank=True, max_length=100, null=True)),
                ('average_deck_height_m', models.FloatField(blank=True, null=True)),
                ('deck_type', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.vesselparticulars')),
            ],
            options={
                'ordering': ['deck_id'],
                'unique_together': {('vessel', 'deck_id')},
            },
        ),
    ]
